version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=webproje
      - MYSQL_USER=root
      - MYSQL_PASSWORD=1234
    depends_on:
      - db

  db:
    image: mysql:latest
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: webproje
      MYSQL_USER: root
      MYSQL_PASSWORD: 1234

volumes:
  mysql_data:
